import './style.css';

const lessons = [
  { id: 'client-opening', theme: 'Client call survival', tag: 'CL', title: 'Sound confident before you say hello.', prompt: 'Your overseas client has just joined. Begin the call with calm authority.', sentence: 'Thanks for making the time today. I’m looking forward to hearing your perspective.', note: 'Starting with “Thanks for making the time” gives you a confident first beat. Let it land before your next sentence.', words: { Thanks: 'A warm, professional opening that acknowledges someone’s time.', perspective: 'A person’s point of view or professional opinion.' } },
  { id: 'appraisal', theme: 'The appraisal battleground', tag: 'AB', title: 'Make your impact impossible to miss.', prompt: 'Your manager asks what you delivered this quarter. Own your contribution with evidence.', sentence: 'I led the launch from planning through delivery, and the team exceeded our target by eighteen percent.', note: 'Specific evidence sounds more credible than broad claims. Name your role, then the outcome.', words: { led: 'Took responsibility for guiding a piece of work.', exceeded: 'Went beyond an expected result or target.' } },
  { id: 'de-jargon', theme: 'Buzzword bingo', tag: 'BJ', title: 'Say it plainly. People will listen.', prompt: 'Your team needs a decision today. Replace a vague phrase with a direct request.', sentence: 'Let’s decide who owns the next step before we finish this meeting.', note: 'Direct language creates action. A clear owner and next step are better than “circling back.”', words: { owns: 'Has clear responsibility for a task or outcome.', decide: 'Make a choice after considering options.' } },
  { id: 'interview', theme: 'Interview & exit strategies', tag: 'IE', title: 'Tell your story without apologising.', prompt: 'A recruiter asks why you are changing roles. Give a positive, forward-looking answer.', sentence: 'I’m ready for a role where I can deepen my client leadership and contribute at a larger scale.', note: 'Keep your answer future-focused. You do not need to criticise your current employer.', words: { deepen: 'Develop a skill or relationship to a more advanced level.', contribute: 'Add useful work, ideas, or value to a group.' } }
];
const storageKey = 'corplingua-state-v1';
const defaultState = { active: 'practice', selected: 0, completed: [], scores: [], streak: 7, name: 'Alex', goal: 4, notifications: true };
let state = loadState(); let speech = null; let listening = false;
const app = document.querySelector('#app'); const live = document.querySelector('#live-region');
function loadState() { try { return { ...defaultState, ...JSON.parse(localStorage.getItem(storageKey)) }; } catch { return { ...defaultState }; } }
function saveState() { localStorage.setItem(storageKey, JSON.stringify(state)); }
function announce(message) { live.textContent = message; }
function icon(name) { return ({ practice: '⌁', progress: '◷', profile: '◉', play: '▶', mic: '●', check: '✓', spark: '✦', close: '×' })[name] || '•'; }
function layout(content) { return `<main class="app-shell"><header class="topbar"><button class="brand" data-action="home" aria-label="CorpLingua home"><span class="brand-mark">C</span>CorpLingua</button><button class="streak" data-action="show-progress" aria-label="${state.streak} day streak">${icon('spark')} <strong>${state.streak}</strong></button></header>${content}<nav class="bottom-nav" aria-label="Primary navigation">${['practice','progress','profile'].map(tab => `<button class="${state.active === tab ? 'active' : ''}" data-nav="${tab}" aria-current="${state.active === tab ? 'page' : 'false'}">${icon(tab)}<span>${tab}</span></button>`).join('')}</nav></main>`; }
function practiceView() {
  const lesson = lessons[state.selected], completed = state.completed.includes(lesson.id), percent = Math.round(state.completed.length / lessons.length * 100);
  const tokens = lesson.sentence.split(' ').map(raw => { const word = raw.replace(/[^A-Za-z’]/g, ''); return lesson.words[word] ? `<button class="word-known" data-define="${word}">${raw}</button>` : `<span>${raw}</span>`; }).join('');
  return layout(`<section class="hero"><p class="eyebrow">TODAY'S 4-MINUTE PRACTICE</p><div class="hero-heading"><span class="module-icon">${lesson.tag}</span>${lesson.theme.toUpperCase()}</div><h1>${lesson.title}</h1><p class="lede">Build a sharper professional voice one calm, useful phrase at a time.</p><div class="progress-row"><span>${state.completed.length} of ${lessons.length} complete</span><div class="progress"><i style="width:${percent}%"></i></div><span>${percent}%</span></div></section><section class="lesson-card"><div class="card-top"><p class="eyebrow">SAY IT OUT LOUD</p><button class="text-button" data-action="why">WHY THIS WORKS</button></div><p class="prompt">${lesson.prompt}</p><blockquote>“${lesson.sentence}”</blockquote><div class="word-strip" aria-label="Tap highlighted words to define them">${tokens}</div><button class="listen-button" data-action="listen">${icon('play')} Listen to the model answer</button><button class="record-button" data-action="record"><span class="record-dot">${icon('mic')}</span><span id="record-label">${completed ? 'Practice again' : 'Speak this phrase'}</span><span class="record-time">${completed ? 'DONE' : '00:12'}</span></button><p id="feedback" class="feedback">${completed ? '<strong>Lesson complete.</strong> Repeat it whenever you need a quick confidence reset.' : 'Use your microphone for feedback, or tap to rehearse and receive a coaching cue.'}</p></section><section class="insight"><p class="eyebrow">ONE SMALL SHIFT</p><h2>Trade filler for a pause.</h2><p>${lesson.note}</p></section><section class="next-card"><div><p class="eyebrow">UP NEXT</p><strong>${lessons[(state.selected + 1) % lessons.length].theme}</strong></div><button class="circle-button" data-action="next" aria-label="Next lesson">→</button></section>`);
}
function progressView() { const avg = state.scores.length ? Math.round(state.scores.reduce((a,b) => a+b, 0) / state.scores.length) : 0; return layout(`<section class="page-heading"><p class="eyebrow">YOUR DEVELOPMENT</p><h1>Small practice.<br>Visible progress.</h1><p>Track the skills that make your professional voice more effective.</p></section><section class="metrics"><article><span>${state.streak}</span><small>day streak</small></article><article><span>${state.completed.length}</span><small>lessons done</small></article><article><span>${avg || '—'}</span><small>avg. score</small></article></section><section class="panel"><div class="section-title"><div><p class="eyebrow">WEEKLY GOAL</p><h2>${state.completed.length} / ${state.goal} sessions</h2></div><span class="goal-badge">${Math.min(100, Math.round(state.completed.length / state.goal * 100))}%</span></div><div class="goal-bars">${[0,1,2,3,4,5,6].map(i => `<i class="${i < Math.min(state.completed.length, 7) ? 'done' : ''}"></i>`).join('')}</div><p class="muted">You’re building a habit. One four-minute session is enough for today.</p></section><section class="panel"><p class="eyebrow">LESSON LIBRARY</p><div class="lesson-list">${lessons.map((lesson,index) => `<button class="lesson-row" data-lesson="${index}"><span class="lesson-tag">${state.completed.includes(lesson.id) ? icon('check') : lesson.tag}</span><span><strong>${lesson.theme}</strong><small>${state.completed.includes(lesson.id) ? 'Completed' : 'Ready to practise'}</small></span><span>→</span></button>`).join('')}</div></section>`); }
function profileView() { return layout(`<section class="page-heading profile-heading"><div class="avatar">${state.name.slice(0,1)}</div><p class="eyebrow">YOUR PROFILE</p><h1>${state.name}</h1><p>Build a communication practice that fits your working life.</p></section><section class="panel settings"><button data-action="edit-name"><span>Display name</span><strong>${state.name} <i>›</i></strong></button><button data-action="set-goal"><span>Weekly lesson goal</span><strong>${state.goal} sessions <i>›</i></strong></button><button data-action="notifications"><span>Practice reminders</span><strong class="toggle ${state.notifications ? 'on' : ''}" aria-label="${state.notifications ? 'On' : 'Off'}"><i></i></strong></button></section><section class="panel"><p class="eyebrow">YOUR FOCUS AREAS</p><div class="chips">${lessons.map(l => `<span>${l.theme}</span>`).join('')}</div></section><button class="reset-button" data-action="reset">Reset local progress</button>`); }
function render() { app.innerHTML = state.active === 'progress' ? progressView() : state.active === 'profile' ? profileView() : practiceView(); bindEvents(); }
function modal(title, body, action = '') { document.querySelector('#modal')?.remove(); document.body.insertAdjacentHTML('beforeend', `<dialog id="modal" class="modal"><button class="modal-close" data-action="close-modal" aria-label="Close">${icon('close')}</button><p class="eyebrow">CORPLINGUA</p><h2>${title}</h2><div class="modal-body">${body}</div>${action}</dialog>`); document.querySelector('#modal').showModal(); }
function bindEvents() { document.querySelectorAll('[data-nav]').forEach(b => b.addEventListener('click', () => { state.active = b.dataset.nav; saveState(); render(); })); document.querySelectorAll('[data-lesson]').forEach(b => b.addEventListener('click', () => { state.selected = Number(b.dataset.lesson); state.active = 'practice'; saveState(); render(); window.scrollTo(0,0); })); document.querySelectorAll('[data-define]').forEach(b => b.addEventListener('click', () => { const lesson = lessons[state.selected]; modal(b.dataset.define, `<p>${lesson.words[b.dataset.define]}</p>`); })); document.querySelectorAll('[data-action]').forEach(b => b.addEventListener('click', () => handleAction(b.dataset.action))); }
function handleAction(action) { const lesson = lessons[state.selected]; if (action === 'home') { state.active='practice'; render(); } if (action === 'show-progress') { state.active='progress'; render(); } if (action === 'next') { state.selected=(state.selected+1)%lessons.length; saveState(); render(); window.scrollTo(0,0); } if (action === 'why') modal('Why this works', `<p>${lesson.note}</p><p>We focus on one phrase at a time so you can use it naturally in a real conversation.</p>`); if (action === 'listen') speak(lesson.sentence); if (action === 'record') startPractice(lesson); if (action === 'close-modal') document.querySelector('#modal')?.close(); if (action === 'edit-name') modal('What should we call you?', `<label class="input-label">Display name<input id="name-input" maxlength="24" value="${state.name}" /></label>`, '<button class="solid-button" data-action="save-name">Save name</button>'); if (action === 'save-name') { const name=document.querySelector('#name-input').value.trim(); if(name){state.name=name;saveState();} document.querySelector('#modal').close();render(); } if (action === 'set-goal') modal('Choose a weekly goal', `<div class="goal-options">${[3,4,5,7].map(goal => `<button data-goal="${goal}" class="${goal===state.goal?'selected':''}">${goal} sessions</button>`).join('')}</div>`); document.querySelectorAll('[data-goal]').forEach(b => b.addEventListener('click', () => { state.goal=Number(b.dataset.goal);saveState();document.querySelector('#modal').close();render(); })); if(action==='notifications'){state.notifications=!state.notifications;saveState();render();announce(`Practice reminders ${state.notifications?'enabled':'disabled'}.`)} if(action==='reset')modal('Reset your progress?', '<p>This clears the lessons and scores saved in this browser. This cannot be undone.</p>', '<button class="danger-button" data-action="confirm-reset">Reset progress</button>'); if(action==='confirm-reset'){state={...defaultState};saveState();document.querySelector('#modal').close();render();} }
function speak(text) { if (!('speechSynthesis' in window)) { announce('Audio playback is not supported in this browser.'); return; } window.speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(text);u.rate=.87;u.onstart=()=>announce('Playing the model answer.');u.onend=()=>announce('Model answer finished.');window.speechSynthesis.speak(u); }
function startPractice(lesson) { if (!('webkitSpeechRecognition' in window || 'SpeechRecognition' in window)) { completeLesson(lesson,88,'Nice rehearsal. Your next cue: slow down slightly before the final clause.');return; } if(listening){speech.stop();return;} const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;speech=new Recognition();speech.lang='en-US';speech.interimResults=false;speech.maxAlternatives=1;listening=true;const label=document.querySelector('#record-label');if(label)label.textContent='Listening…';document.querySelector('.record-button')?.classList.add('recording');announce('Listening for your practice phrase.');speech.onresult=e=>{const heard=e.results[0][0].transcript.toLowerCase();const terms=lesson.sentence.toLowerCase().split(/\W+/).filter(w=>w.length>3);const score=Math.max(62,Math.min(98,Math.round(terms.filter(w=>heard.includes(w)).length/terms.length*100)));completeLesson(lesson,score,`We heard: “${e.results[0][0].transcript}”`)};speech.onerror=()=>completeLesson(lesson,84,'Practice captured. Keep a steady pace and pause briefly between ideas.');speech.onend=()=>{listening=false;document.querySelector('.record-button')?.classList.remove('recording')};speech.start(); }
function completeLesson(lesson,score,message){if(!state.completed.includes(lesson.id))state.completed.push(lesson.id);state.scores.push(score);saveState();render();modal(`${score}/100 clarity score`, `<p>${message}</p><div class="score-grid"><span><b>${score}</b> clarity</span><span><b>${Math.min(100,score+3)}</b> fluency</span><span><b>${Math.max(70,score-4)}</b> tone</span></div><p>Strong work. You completed <b>${lesson.theme}</b>.</p>`, '<button class="solid-button" data-action="close-modal">Keep going</button>');announce(`Lesson complete. Your clarity score is ${score}.`);}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));render();
